#!/usr/bin/env bash
# Generate strong secrets for the self-hosted stack and print a ready-to-edit
# .env to stdout. The ANON_KEY / SERVICE_ROLE_KEY are minted as HS256
# JWTs signed by the generated JWT_SECRET.
#
#   bash gen-secrets.sh > /opt/yah/.env && chmod 600 /opt/yah/.env
#   # then edit the ENABLE_BANKING_* placeholders
#
# Requires: openssl, node. Re-running generates fresh secrets (do not run on a
# live deployment unless you intend to rotate — rotating JWT_SECRET invalidates
# existing sessions and requires re-minting the keys).
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

JWT_SECRET="$(openssl rand -hex 32)"                 # 64 chars (>= 32 required)
POSTGRES_PASSWORD="$(openssl rand -hex 24)"
SECRET_KEY_BASE="$(openssl rand -hex 32)"            # 64 chars (Realtime)
PG_META_CRYPTO_KEY="$(openssl rand -hex 16)"         # 32 chars
DASHBOARD_PASSWORD="$(openssl rand -hex 16)"
CRON_SECRET="$(openssl rand -hex 32)"
TOKEN_ENCRYPTION_KEY="$(openssl rand -base64 32)"    # app: bank-token encryption

ANON_KEY="$(JWT_SECRET="$JWT_SECRET" node "$here/mint-jwt.mjs" anon)"
SERVICE_ROLE_KEY="$(JWT_SECRET="$JWT_SECRET" node "$here/mint-jwt.mjs" service_role)"

cat <<ENV
############################################################
# Generated by deploy/gen-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# REVIEW the Enable Banking placeholders below, then save as /opt/yah/.env (0600)
############################################################

############
# Domain & public URLs
############
APP_DOMAIN=yah.thatsmyhuman.ai
NEXT_PUBLIC_SUPABASE_URL=https://api.yah.thatsmyhuman.ai
NEXT_PUBLIC_APP_URL=https://yah.thatsmyhuman.ai
SUPABASE_PUBLIC_URL=https://api.yah.thatsmyhuman.ai
API_EXTERNAL_URL=https://api.yah.thatsmyhuman.ai
SITE_URL=https://yah.thatsmyhuman.ai
ADDITIONAL_REDIRECT_URLS=https://yah.thatsmyhuman.ai
# Server-side Supabase traffic goes straight to Kong over the compose network.
SUPABASE_INTERNAL_URL=http://kong:8000

############
# Deployment (CI overwrites this on every deploy)
############
IMAGE_TAG=

############
# Enable Banking (EDIT THESE — from https://enablebanking.com/cp)
# Private key is the base64 of the full PEM: base64 < private.pem | tr -d '\n'
############
ENABLE_BANKING_APPLICATION_ID=your-application-id
ENABLE_BANKING_PRIVATE_KEY_B64=base64-of-private-key-pem
ENABLE_BANKING_BASE_URL=https://api.enablebanking.com

############
# Generated secrets (do not edit)
############
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
JWT_SECRET=$JWT_SECRET
ANON_KEY=$ANON_KEY
SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
SECRET_KEY_BASE=$SECRET_KEY_BASE
PG_META_CRYPTO_KEY=$PG_META_CRYPTO_KEY
CRON_SECRET=$CRON_SECRET
TOKEN_ENCRYPTION_KEY=$TOKEN_ENCRYPTION_KEY

############
# Dashboard (Studio) basic-auth — Studio is SSH-tunnel only
############
DASHBOARD_USERNAME=supabase
DASHBOARD_PASSWORD=$DASHBOARD_PASSWORD

############
# Postgres
############
POSTGRES_HOST=db
POSTGRES_DB=postgres
POSTGRES_PORT=5432

############
# Auth (email/password, autoconfirm — no SMTP)
############
DISABLE_SIGNUP=false
JWT_EXPIRY=3600
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=true
ENABLE_ANONYMOUS_USERS=false
ENABLE_PHONE_SIGNUP=false
ENABLE_PHONE_AUTOCONFIRM=false
# Autoconfirm is on, so these are never used — harmless stubs keep compose quiet.
SMTP_ADMIN_EMAIL=admin@example.com
SMTP_HOST=localhost
SMTP_PORT=2500
SMTP_USER=fake
SMTP_PASS=fake
SMTP_SENDER_NAME=yah
MAILER_URLPATHS_CONFIRMATION=/auth/v1/verify
MAILER_URLPATHS_INVITE=/auth/v1/verify
MAILER_URLPATHS_RECOVERY=/auth/v1/verify
MAILER_URLPATHS_EMAIL_CHANGE=/auth/v1/verify

############
# Studio / Kong / PostgREST
############
STUDIO_DEFAULT_ORGANIZATION=yah
STUDIO_DEFAULT_PROJECT=yah
STUDIO_HOST_PORT=8001
OPENAI_API_KEY=
KONG_HTTP_PORT=8000
PGRST_DB_SCHEMAS=public,storage,graphql_public
PGRST_DB_MAX_ROWS=1000
PGRST_DB_EXTRA_SEARCH_PATH=public

############
# Storage / imgproxy / functions (kept at defaults; app does not use Storage)
############
GLOBAL_S3_BUCKET=stub
REGION=stub
STORAGE_TENANT_ID=stub
S3_PROTOCOL_ACCESS_KEY_ID=
S3_PROTOCOL_ACCESS_KEY_SECRET=
IMGPROXY_AUTO_WEBP=true
FUNCTIONS_VERIFY_JWT=false

############
# Optional new-style opaque / asymmetric keys (unused — legacy HS256 path).
############
SUPABASE_PUBLISHABLE_KEY=
SUPABASE_SECRET_KEY=
ANON_KEY_ASYMMETRIC=
SERVICE_ROLE_KEY_ASYMMETRIC=
JWT_KEYS=
JWT_JWKS=
ENV
